# Generated by Django 2.2 on 2019-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Out of Service', 'Out of Service')], default='Available', max_length=20)),
            ],
        ),
    ]
