# Generated by Django 2.2 on 2019-05-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
