# Generated by Django 2.2 on 2019-05-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_room_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_notes',
            new_name='notes',
        ),
    ]
