# Generated by Django 2.2 on 2019-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20190513_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Out of Service', 'Out of Service')], max_length=20),
        ),
    ]
