# Generated by Django 2.2 on 2019-05-15 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20190514_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120, unique=True)),
                ('sleepable', models.BooleanField(default=False)),
                ('number_it_sleeps', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
