# Generated by Django 2.2 on 2019-05-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_furniture'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.Room'),
            preserve_default=False,
        ),
    ]
