# Generated by Django 2.2 on 2019-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_furniture_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='room',
        ),
        migrations.AddField(
            model_name='furniture',
            name='rooms',
            field=models.ManyToManyField(to='hotel.Room'),
        ),
    ]
