# Generated by Django 2.2 on 2019-05-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20190515_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='rooms',
            field=models.ManyToManyField(related_name='furniture', to='hotel.Room'),
        ),
    ]
