# Generated by Django 2.2 on 2019-05-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20190515_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='rooms',
            field=models.ManyToManyField(to='hotel.Room'),
        ),
    ]
