# Generated by Django 2.2 on 2019-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_guest_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_reserved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_reserved',
            field=models.ManyToManyField(to='hotel.Room'),
        ),
    ]
