# Generated by Django 2.2 on 2019-06-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20190612_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room_statuses', models.CharField(default='{reserved:[], checkIns:[], checkOuts:[], staying:[], available:[], outofservice:[]}', max_length=2000)),
            ],
        ),
    ]
