# Generated by Django 2.2 on 2019-06-22 17:39

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_dailyactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
        HStoreExtension(),
        migrations.AlterField(
            model_name='dailyactivity',
            name='room_statuses',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
