# Generated by Django 2.2 on 2019-06-23 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_auto_20190622_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='res_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
