# Generated by Django 2.2 on 2019-06-23 01:48

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('hotel', 'Reservation')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_reservation_res_id'),
    ]

    operations = [
    	migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
