# Generated by Django 2.2 on 2019-06-23 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_auto_20190622_1848'),
    ]

    operations = [
    	migrations.AlterField(
            model_name='reservation',
            name='res_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
